### ISSUE TITLE
Bug on basic initiallization code

### ISSUE THREAD

**Issue by alvaroalvarezih** [ThunderTecke/PID_Py#1]
Hello,

Thanks for the project. I've just installed it to try, and just calling:

`pid = PID(kp = 10.0, ki = 5.0, kd = 0.0) `

I've got an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\.conda\envs\Py310\lib\site-packages\PID_Py\PID.py", line 235, in __init__
    if HistorianParams.P in self.historianParams:
TypeError: argument of type 'NoneType' is not iterable
```

Its seems to be a bug. Can you confirm? 
Thanks!

**Comment by ThunderTecke** [comment]
Hello,

Thank you for your feedback.
I'll check that soon, but I think it's a bug.

In the meantime, you can use the following.
`pid = PID(kp = 10.0, ki = 5.0, kd = 0.0, historianParameters = HistorianParameters.P)`

You can find more information about historian [here](https://github.com/ThunderTecke/PID_Py#historian)

**Comment by alvaroalvarezih** [comment]
Thanks, 
it seems that you also changed at some point from HistorianParameters --> HistorianParams, and this should be updated also on the docs

**Comment by ThunderTecke** [comment]
Oh ! You're right. I'll do that at the same time.
Thank you

**Comment by ThunderTecke** [comment]
Hello,

I have just uploaded PID_Py V1.1.1. Let me know if everything is correct.

ThunderTecke

**Comment by alvaroalvarezih** [comment]
Dear ThunderTecke

I tried it again, and works now!!
Thanks

Álvaro

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
