### ISSUE TITLE
Error on circular buffer self.historian["P"]

### ISSUE THREAD

**Issue by alvaroalvarezih** [ThunderTecke/PID_Py#3]
Dear ThunderTecke,

I am employing your lib, which is a very good implementation of a PID control.
However, I was experiencing some issues when was running for long time periods.
I found the following error on the code:
   
```python
Exception in thread Thread-3:
Traceback (most recent call last):
  File "d:\ihgit\pyA0Hidro.acquisition\pyInstruments\EPR60 MicrostepDriver\EPR60_Actuator.py", line 403, in set_rpm
    command = self.pid(setpoint = next_position, processValue = pos)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PID_Py\PID.py", line 566, in __call__
    return self.compute(setpoint, processValue, currentTime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\PID_Py\PID.py", line 483, in compute
    del self.historianLenght["P"][0]
        ~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'int' object is not subscriptable     
``` 

And I found that in PID.py line 483:

```python
            # ===== Historian =====
            if self.historian is not None:
                if HistorianParams.P in self.historianParams:
                    self.historian["P"].append(self._p)
                    
                    if len(self.historian["P"]) > self.historianLenght:
                        del self.historianLenght["P"][0]
``` 

It is an errata, since you probably aim to remove the first element of self.historian["P"] --> self.historian["P"][0] rather than self.historianLenght["P"][0] since self.historianLenght is an int set by default to 100000 (this is why it just happens for long periods).

Hope this comment helps!
Thanks again
Alvaro

**Comment by alvaroalvarezih** [comment]
same applies to lines:
489: del self.historianLenght["I"][0]
495: del self.historianLenght["D"][0]
501: del self.historianLenght["OUTPUT"][0]
507: del self.historianLenght["SETPOINT"][0]
513: del self.historianLenght["PROCESS_VALUE"][0]
519: del self.historianLenght["ERROR"][0]
525: del self.historianLenght["TIME"][0]

**Comment by ThunderTecke** [comment]
Thank you for your feedback.

I will check that, and give you an update. Let me take a look this evening after my job 😊

In the meantime, I'm interested to know what project you're using it for 😉 and how you are using my PID.

Feel free to suggest enhancement or comment.

Best regards,
ThunderTecke

**Comment by alvaroalvarezih** [comment]
I am using it to perform the control of a linear actuator based on the position feedback. Since I am able to measure the current position and the expected next one, I use it to establish the next position with a optmized Kp, Ki and Kd

**Comment by ThunderTecke** [comment]
Interesting 😊
Thank you

**Comment by ThunderTecke** [comment]
Hi,
You can update PID_Py. Let me know if there's still a problem 😊
I will close the issue in some days, if I haven't news

Best regards

**Comment by institutohidraulica** [comment]
I have checked it and seems to be solved!

Thanks again

**Comment by alvaroalvarezih** [comment]
I have checked it and seems to be solved!!

Thanks again

**Comment by ThunderTecke** [comment]
Nice 

Best regards 😊
